// src/components/HelloWorld/index.tsx
import { FC, useState } from 'react'
import dayjs from 'dayjs'
import './index.scss'
interface Props {
  msg: string
}
const App: FC<Props> = (props) => {
  const { msg } = props
  const date = useState(dayjs().format('YYYY-MM-DD'))
  return (
    <div className="component">
      <div className="title text-4xl">{msg}</div>
      <div className="date">{date}</div>
    </div>
  )
}

export default App

// src/components/HelloWorld.vue
<template>
  <div class="component">
    <div class="title text-4xl">{{ msg }}</div>
    <div class="date">{{ date }}</div>
  </div>
</template>
<script lang="ts" setup>
import dayjs from 'dayjs'
const date = ref(dayjs().format('YYYY-MM-DD'))
defineProps({
  msg: { type: String, default: 'hello, world' }
})
</script>
<style lang="scss" scoped>
.component {
  .title {
  }
  .date {
    margin-top: 15px;
  }
}
</style>
